### ISSUE TITLE
Kactus previews folder is unmanageable

### ISSUE THREAD

**Issue by saskiae** [kactus-io/kactus#123]
## Description
Currently having problems with my hard drive space (500GB SSD) and tracked down one part of the problem to Kactus previews. My Kactus previews folder is currently 65GB. It would be awesome if it were possible to add a setting to delete Kactus preview files that are older than a day.

## Version
* Kactus:
0.3.14
* Operating system:
macOS Mojave 10.14.1

## Steps to Reproduce
I used a disk sweeper tool and found the folder under Users/~Username/Library/Application Support/Kactus/previews

Thank you :)

**Comment by mathieudutour** [comment]
Good point, I should add a button to clear the cache :+1:

**Comment by mathieudutour** [comment]
So the preview folder is there to cache the different previews that Kactus generates.

I'll try to think of a way to clear the cache automatically but it's not trivial, we need to keep a balance between keeping the ones you see pretty often and the ones you won't need anymore

**Comment by mathieudutour** [comment]
What I could do is that when a preview folder is older than 3 days, I remove it. Maybe with a setting to control that period

**Comment by danielalmeidagoncalves** [comment]
Yes you are right @mathieudutour. I think we could manage by having the button to explicitly clear the cache when the user wants to do so, and maybe having a configuration to choose it to be automatically and at the same time warning the user that could generate more loading scenarios within the app because of these preview builds. 
Nevertheless I think as a first approach the clean button along side with maybe a information of the size of the previews could be a very good first implementation.

**Comment by mathieudutour** [comment]
should be fixed in 0.3.15
