### ISSUE TITLE
Question: is it possible to checkout an older commit?

### ISSUE THREAD

**Issue by lyquix-owner** [kactus-io/kactus#136]
One of the features we were hoping to get by introducing git into our graphic design workflow is the ability to restore a file as it was at some point in the past. Having this ability allows us to not have to worry about keeping multiple versions of design files, or keeping outdated elements within files just in case they may be needed in the future.

However, we don't see a way in Kactus to checkout a previous commit.

Am I missing something or is this intentional.

Thank you!

**Comment by mathieudutour** [comment]
It's not possible to checkout a commit in kactus but you can open a Sketch file like it was in a specific commit: 
![image](https://user-images.githubusercontent.com/3254314/65694551-5480ca00-e076-11e9-8d83-cb4bd11b7b4e.png)

**Comment by lyquix-owner** [comment]
Oh got it... thank you... I was clicking directly on the .sketch file and when I do that the Open Sketch File button is not displayed. It is only displayed when clicking on any of the sub-files.

**Comment by mathieudutour** [comment]
Clicking on the `.sketch` file? You probably don't want to keep the sketch files in git, and let Kactus recreate them from the json files (otherwise it will create merge conflicts all the time and that would counteract the whole point of Kactus). 
Here is how to remove them from git: https://kactus.io/help/how-to/#existing-repos

**Comment by lyquix-owner** [comment]
I see. The repo was empty but it wasn't created in Kactus, so we didn't have the necessary .gitignore.

Thank you!
