### ISSUE TITLE
View to resolve conflicts

### ISSUE THREAD

**Issue by uiuxcafe** [kactus-io/kactus#30]
Hi,

Is there any way to solve conflicts resulting from editing the same object attributes (e.g. two people both change color)?

It seemed to me the UI can't handle this. It didn't show exactly where the conflict actually happened. Any idea? Thanks.

**Comment by mitsuyoshi-yamazaki** [comment]
I want to ask about conflict too.
It seems like only JSON files conflict and the sketch file doesn’t.

- why the sketch file doesn’t conflict (= what is the relationship between Sketch file and JSON? how do them work?
- is there good way to resolve JSON conflicts?
  - JSON dictionary doesn’t sort its keys so the keys are rearranged and conflict

**Comment by mathieudutour** [comment]
* the sketch files are not tracked with git so they won't conflicts. (they would conflict all the time otherwise)
* the keys should be sorted since v0.1.8 tho. There is no easy way to resolve the conflicts yet. I should probably work on an UI to pick either conflicting version or allowing to open a text editor to merge manually in either version is not good

**Comment by mathieudutour** [comment]
fixed in v0.3.0 :tada:
